import DemoActivityProvider from "./DemoActivityProvider.js";

class BehavioralAnalysisService {
  /**
   * Helper to parse time string like "08:30" to minutes from midnight
   */
  parseTime(timeStr) {
    if (!timeStr) return 0;
    const [hours, minutes] = timeStr.split(":").map(Number);
    return hours * 60 + (minutes || 0);
  }

  /**
   * Calculate baseline from historical events
   */
  calculateBaseline(user, baselineEvents) {
    const knownDevices = user.normalDevices || [];
    const typicalLoginHours = user.normalWorkingHours || { start: "09:00", end: "17:00" };

    let totalFileAccess = 0;
    let totalDataTransfer = 0;
    let firstEventTime = null;
    let lastEventTime = null;

    for (const event of baselineEvents) {
      const time = new Date(event.timestamp).getTime();
      if (!firstEventTime || time < firstEventTime) firstEventTime = time;
      if (!lastEventTime || time > lastEventTime) lastEventTime = time;

      if (event.activityType === "FILE_ACCESS") {
        totalFileAccess++;
      }
      if (event.activityType === "FILE_DOWNLOAD" || event.activityType === "FILE_UPLOAD") {
        if (event.metadata && event.metadata.bytesTransferred) {
          totalDataTransfer += event.metadata.bytesTransferred;
        }
      }
    }

    // Calculate baseline duration in days (minimum 1 day to avoid Infinity)
    let baselineDays = 1;
    if (firstEventTime && lastEventTime && lastEventTime > firstEventTime) {
      baselineDays = Math.max((lastEventTime - firstEventTime) / (1000 * 60 * 60 * 24), 1);
    }

    return {
      typicalLoginHours,
      knownDevices,
      averageDailyFileAccess: Math.round(totalFileAccess / baselineDays),
      averageDailyDataTransfer: Math.round(totalDataTransfer / baselineDays),
    };
  }

  /**
   * Analyze user behavior
   */
  async analyzeUser(userId, analysisStart, analysisEnd) {
    const user = await DemoActivityProvider.getDemoUser(userId);
    if (!user) {
      throw new Error(`User not found: ${userId}`);
    }

    // Determine Analysis Window
    let start, end;
    if (analysisStart && analysisEnd) {
      start = new Date(analysisStart);
      end = new Date(analysisEnd);
    } else {
      // Fetch latest event for user to determine window dynamically
      const latestEvents = await DemoActivityProvider.getActivitiesByUser(userId, {}, { limit: 1 });
      if (latestEvents.length > 0) {
        end = new Date(latestEvents[0].timestamp);
      } else {
        end = new Date();
      }
      start = new Date(end.getTime() - 24 * 60 * 60 * 1000); // 24 hours prior
    }

    // Fetch baseline events (all events before 'start')
    // Since getActivitiesByUser only takes startDate and endDate loosely, we might need a custom query
    // Actually, getActivitiesByUser allows passing filters. 
    // We can fetch baseline as { endDate: start }
    const baselineEvents = await DemoActivityProvider.getActivitiesByUser(userId, { endDate: start.toISOString() }, { limit: 10000 });
    
    // Fetch analysis events
    const analysisEvents = await DemoActivityProvider.getActivitiesByUser(userId, { startDate: start.toISOString(), endDate: end.toISOString() }, { limit: 10000 });

    const baseline = this.calculateBaseline(user, baselineEvents);

    // Initialize Signals
    const signals = {
      unusualLoginTime: false,
      newDevice: false,
      abnormalFileAccess: false,
      abnormalDataTransfer: false,
      sensitiveResourceAccess: false
    };
    const explanations = [];

    const expectedStartMinutes = this.parseTime(baseline.typicalLoginHours.start);
    const expectedEndMinutes = this.parseTime(baseline.typicalLoginHours.end);

    let analysisFileAccess = 0;
    let analysisDataTransfer = 0;

    for (const event of analysisEvents) {
      // UNUSUAL_LOGIN_TIME
      if (event.activityType === "LOGIN" && !signals.unusualLoginTime) {
        const eventDate = new Date(event.timestamp);
        // Using UTC hours as generated by seed (it fakes time by setting UTC hour to 1-4 for anomalies)
        const eventMinutes = eventDate.getUTCHours() * 60 + eventDate.getUTCMinutes();
        
        // Simple check if outside window
        if (eventMinutes < expectedStartMinutes || eventMinutes > expectedEndMinutes) {
          signals.unusualLoginTime = true;
          explanations.push(`Login occurred outside the user's normal working hours. (Observed: ${eventDate.getUTCHours()}:${eventDate.getUTCMinutes().toString().padStart(2, '0')} UTC)`);
        }
      }

      // NEW_DEVICE
      if (event.deviceId && !baseline.knownDevices.includes(event.deviceId) && !signals.newDevice) {
        signals.newDevice = true;
        explanations.push(`A previously unseen device was observed: ${event.deviceId}`);
      }

      // SENSITIVE_RESOURCE_ACCESS
      if (event.activityType === "SENSITIVE_RESOURCE_ACCESS" && !signals.sensitiveResourceAccess) {
        signals.sensitiveResourceAccess = true;
        explanations.push(`A sensitive resource was accessed: ${event.resource}`);
      }

      // Aggregate volume metrics
      if (event.activityType === "FILE_ACCESS") {
        analysisFileAccess++;
      }
      if (event.activityType === "FILE_DOWNLOAD" || event.activityType === "FILE_UPLOAD") {
        if (event.metadata && event.metadata.bytesTransferred) {
          analysisDataTransfer += event.metadata.bytesTransferred;
        }
      }
    }

    // ABNORMAL_FILE_ACCESS threshold: > 3x average, min 10
    const fileAccessThreshold = Math.max(baseline.averageDailyFileAccess * 3, 10);
    if (analysisFileAccess > fileAccessThreshold) {
      signals.abnormalFileAccess = true;
      explanations.push(`File access volume (${analysisFileAccess}) exceeded the user's historical baseline average (${baseline.averageDailyFileAccess}).`);
    }

    // ABNORMAL_DATA_TRANSFER threshold: > 3x average, min 100MB
    const dataTransferThreshold = Math.max(baseline.averageDailyDataTransfer * 3, 100 * 1024 * 1024);
    if (analysisDataTransfer > dataTransferThreshold) {
      signals.abnormalDataTransfer = true;
      explanations.push(`Data transfer volume (${Math.round(analysisDataTransfer / (1024*1024))} MB) exceeded the historical baseline.`);
    }

    return {
      userId,
      analysisWindow: {
        start: start.toISOString(),
        end: end.toISOString()
      },
      baseline,
      signals,
      explanations,
      analyzedEventCount: analysisEvents.length
    };
  }
}

export default new BehavioralAnalysisService();
